engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: .eslintrc.json
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript

ratings:
  paths:
    - "**/**.js"
